language: go

services:
  - docker

before_install:
  - travis_retry curl -sf https://up.apex.sh/install | bash

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u=hendry -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    edge: true
    script: make
    on:
      branch: master
  - provider: script
    edge: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

env:
  - GO111MODULE=on
